apiVersion: v1
kind: Namespace
metadata:
  name: cloudlabs-webapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sa
  namespace: cloudlabs-webapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-sa-clusterrolebinding
  namespace: cloudlabs-webapp
subjects:
- kind: ServiceAccount
  name: secret-sa
  namespace: cloudlabs-webapp
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: secret-role
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-role
  namespace: cloudlabs-webapp
rules:
- apiGroups: ["*"]
  resources: ["serviceaccounts","serviceaccounts/token"]
  verbs: ["*"]
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: vul-app
  name: vul-app
  namespace: cloudlabs-webapp
spec:
  replicas: 1
  selector:
    name: vul-app
  template:
    metadata:
      labels:
        name: vul-app
    spec:
      serviceAccountName: secret-sa
      containers:
      - image: chrisley75/vul-app:2.0.0
        name: vul-app
        ports:
        - containerPort: 5000
          name: http-server
---
apiVersion: v1
kind: Service
metadata:
  name: vul-app-svc
  namespace: cloudlabs-webapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: vul-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-sa
  namespace: cloudlabs-webapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: cluster-admin-sa
  namespace: cloudlabs-webapp
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""